version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: dockerFile
    container_name: app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"  
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ../Shopping-cart:/usr/src/app
    depends_on:
      - db
      - redis
    networks:
      - shopping_cart
  
  db:
    image: mysql:8.0
    container_name: database
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    expose:
      - 3308
    ports:
      - 3308:3306
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - shopping_cart

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - shopping_cart

networks:
  shopping_cart:
    driver: bridge
  
